[platformio]
default_envs = esp32c3

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
lib_deps =
    bblanchon/ArduinoJson@^7.2.0
    knolleary/PubSubClient@^2.8
    adafruit/Adafruit BME280 Library@^2.3.0
    adafruit/Adafruit BMP280 Library@^2.6.8
extra_scripts = pre:scripts/version.py
build_flags =
    -DCORE_DEBUG_LEVEL=1

[env:esp32c3]
board = esp32-c3-devkitm-1
board_build.partitions = min_spiffs.csv
build_flags =
    ${env.build_flags}
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DPOGSENSOR_DEFAULT_SDA=6
    -DPOGSENSOR_DEFAULT_SCL=5

[env:esp32s3]
board = esp32-s3-devkitc-1
board_build.partitions = partitions_ota.csv
build_flags =
    ${env.build_flags}
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DPOGSENSOR_DEFAULT_SDA=8
    -DPOGSENSOR_DEFAULT_SCL=9

[env:esp32dev]
board = esp32dev
board_build.partitions = min_spiffs.csv
build_flags =
    ${env.build_flags}
    -DPOGSENSOR_DEFAULT_SDA=21
    -DPOGSENSOR_DEFAULT_SCL=22
